server:
  port: 6701

spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
      server:
        git:
          uri: https://github.com/luotongxi/lala-cloud-config.git
          
eureka:
  instance:
    hostname: configserver
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/

user:
  username: luotong
  password: 111111

---
server:
  port: 6701
  
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luotongxi/lala-cloud-config.git
          
eureka:
  instance:
    hostname: configserver
    perferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:6702/eureka/
