server:
  port: 16100

spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luotongxi/lala-cloud-config

---
server:
  port: 16100
  
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/luotongxi/lala-cloud-config
